

eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
          - id: auth-service
            uri: http://localhost:8090
            predicates:
              - Path=/auth/**
            filters:
              - AuthenticationFilter



          - id: inventory-service
            uri: http://localhost:8092
            predicates:
              - Path=/api/v1/inventory/**
            filters:
              - AuthenticationFilter

          - id: delivery-service
            uri: http://localhost:8093
            predicates:
              - Path=/delivery/**
            filters:
              - AuthenticationFilter

  config:
    import: optional:configserver:http://localhost:8888
management:
  tracing:
    sampling:
      probability: 1.0

