

eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
          - id: auth-service
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/auth/**
          - id: inventory-service
            uri: http://localhost:8092
            predicates:
              - Path=/api/v1/inventory/**
          - id: inventory-service(category)
            uri: http://localhost:8092
            predicates:
              - Path=/api/v1/category/**

  config:
    import: optional:configserver:http://localhost:8888
management:
  tracing:
    sampling:
      probability: 1.0

